require('dotenv').config()
module.exports = {
    GOOGLE_DIALOGFLOW_CLIENT_KEY:process.env.GOOGLE_DIALOGFLOW_CLIENT_KEY,
    MICROSOFT_LUIS_PRIMARY_KEY:process.env.MICROSOFT_LUIS_PRIMARY_KEY,
    MICROSOFT_LUIS_ENDPOINT:process.env.MICROSOFT_LUIS_ENDPOINT,
    MICROSOFT_LUIS_APPID:process.env.MICROSOFT_LUIS_APPID
}